tools: Avoid used-uninitialized warning with some compilers
Seen for armhf with forky toolchain:

In function 'dump_uservars',
    inlined from 'dump_env' at tools/bg_printenv.c:208:3:
tools/bg_printenv.c:127:25: error: 'val_snum' may be used uninitialized [-Werror=maybe-uninitialized]
  127 |                         fprintf(stdout, raw ? "=%lld\n" : " = %lld\n",
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  128 |                                 (long long signed int)val_snum);
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tools/bg_printenv.c: In function 'dump_env':
tools/bg_printenv.c:84:17: note: 'val_snum' was declared here
   84 |         int64_t val_snum;
      |                 ^~~~~~~~
In function 'dump_uservars',
    inlined from 'dump_env' at tools/bg_printenv.c:208:3:
tools/bg_printenv.c:109:25: error: 'val_unum' may be used uninitialized [-Werror=maybe-uninitialized]
  109 |                         fprintf(stdout, raw ? "=%llu\n" : " = %llu\n",
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  110 |                                 (long long unsigned int)val_unum);
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tools/bg_printenv.c: In function 'dump_env':
tools/bg_printenv.c:83:18: note: 'val_unum' was declared here
   83 |         uint64_t val_unum;
      |                  ^~~~~~~~

These are false positives because all possibly type values that are fed
into the switch-cases are handled. But that is not obvious on first
sight, also for humans. So let's help both the compiler and the humans
here.

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>